line-length = 100
fix = true
indent-width = 2
exclude = [".venv", "venv", "build", "dist", "__pycache__", "tests", "examples"]

[lint]
select = ["ALL"]
ignore = [
  "PD",
  "D203",
  "D213",
]
pylint.max-args = 15

[lint.per-file-ignores]
"src/prxteinmpnn/run.py" = ["E402", "PLR0913", "ANN401"]
"src/prxteinmpnn/io/parsers.py" = ["ANN401"]
"src/prxteinmpnn/io/conversion.py" = ["ANN401"]
