"""Host-side factory for constructing InferenceBundle and associated configs."""

from __future__ import annotations

import jax
import jax.numpy as jnp
from typing import Any

from prxteinmpnn.types.bundles import (
    InferenceBundle, GeometryBundle, ConditioningBundle, 
    LigandBundle, WaveScheduleBundle
)
from prxteinmpnn.types.configs import InferenceConfig
from prxteinmpnn.types.stages import StageSet
from prxteinmpnn.inference.logits import LOGIT_STRATEGIES

def build_inference_bundle(
    coords: jax.Array,           # (L, 4, 3) or (S, L, 4, 3)
    mask: jax.Array,             # (L,) or (S, L)
    residue_index: jax.Array,
    chain_index: jax.Array,
    *,
    backbone_noise: float | jax.Array = 0.0,
    backbone_noise_mode: str = "direct",
    sequence: jax.Array | None = None,
    ar_mask: jax.Array | None = None,
    bias: jax.Array | None = None,
    fixed_mask: jax.Array | None = None,
    fixed_tokens: jax.Array | None = None,
    tie_group_map: jax.Array | None = None,
    state_weights: jax.Array | None = None,
    y: jax.Array | None = None,
    y_t: jax.Array | None = None,
    y_m: jax.Array | None = None,
    structure_mapping: jax.Array | None = None,
    temperature: float = 1.0,
    mode: str = "score_conditional",
    strategy: str = "arithmetic_mean",
    strategy_temperature: float = 1.0,
    use_rolling_state: bool = False,
    inference: bool = True,
) -> tuple[InferenceBundle, InferenceConfig, StageSet]:
    """Single entry point for bundle construction from raw arrays."""
    
    # 1. Resolve shapes
    if coords.ndim == 3:
        coords = coords[None, ...]
        mask = mask[None, ...]
        residue_index = residue_index[None, ...]
        chain_index = chain_index[None, ...]
        if structure_mapping is not None:
            structure_mapping = structure_mapping[None, ...]
        if y is not None:
            y = y[None, ...]
            y_t = y_t[None, ...]
            y_m = y_m[None, ...]

    # After normalization, all arrays must be 4D (or 3D for mask/indices, 3D/4D for ligand)
    assert coords.ndim == 4, f"Expected coords.ndim == 4 after normalization, got {coords.ndim}"
    assert mask.ndim == 3, f"Expected mask.ndim == 3 after normalization, got {mask.ndim}"
    assert residue_index.ndim == 3, f"Expected residue_index.ndim == 3 after normalization, got {residue_index.ndim}"
    assert chain_index.ndim == 3, f"Expected chain_index.ndim == 3 after normalization, got {chain_index.ndim}"

    S, L = coords.shape[0], coords.shape[1]
    
    # 2. Geometry
    geo = GeometryBundle(
        coords=coords,
        mask=mask,
        residue_index=residue_index,
        chain_index=chain_index,
        state_flat_rows=jnp.zeros((S, L), dtype=jnp.int32), # TODO: Handle flat rows if needed
        n_states=S,
        n_canonical=L,
        n_flat=L,
        structure_mapping=structure_mapping
    )
    
    # 3. Conditioning
    if state_weights is None:
        state_weights = jnp.ones(S) / S
    
    if tie_group_map is None:
        tie_group_map = jnp.broadcast_to(jnp.arange(L)[None, :], (S, L))
    elif tie_group_map.ndim == 1:
        tie_group_map = jnp.broadcast_to(tie_group_map[None, :], (S, L))
        
    if ar_mask is None:
        if mode == "score_conditional":
            # Default to full context minus self (all-ones except diagonal)
            ar_mask = 1.0 - jnp.eye(L)
            ar_mask = jnp.broadcast_to(ar_mask[None, ...], (S, L, L))
        else:
            # For sampling, it will be generated by the kernel/driver
            ar_mask = jnp.zeros((S, L, L))
    elif ar_mask.ndim == 2:
        ar_mask = jnp.broadcast_to(ar_mask[None, ...], (S, L, L))

    cond = ConditioningBundle(
        fixed_mask=fixed_mask if fixed_mask is not None else jnp.zeros(L),
        fixed_tokens=fixed_tokens if fixed_tokens is not None else jnp.zeros(L, dtype=jnp.int32),
        bias=bias if bias is not None else jnp.zeros((L, 21)),
        tie_group_map=tie_group_map,
        state_weights=state_weights,
        sequence_oh=jax.nn.one_hot(sequence, 21) if sequence is not None else jnp.zeros((L, 21)),
        ar_mask=ar_mask,
        temperature=jnp.array(temperature)
    )
    
    # 4. Ligand
    lig = LigandBundle(
        y=y if y is not None else jnp.zeros((S, 0, 4, 3)),
        y_t=y_t if y_t is not None else jnp.zeros((S, 0, 4), dtype=jnp.int32),
        y_m=y_m if y_m is not None else jnp.zeros((S, 0, 4))
    )
    
    # 5. Assemble Bundle
    bundle = InferenceBundle(
        geometry=geo,
        conditioning=cond,
        ligand=lig,
        wave=WaveScheduleBundle.empty(L),
        backbone_noise=jnp.array(backbone_noise)
    )
    
    # 6. Config
    config = InferenceConfig(
        mode=mode,
        backbone_noise_mode=backbone_noise_mode,
        use_rolling_state=use_rolling_state,
        inference=inference
    )
    
    # 7. StageSet
    strategy_cls = LOGIT_STRATEGIES.get(strategy)
    if strategy == "geometric_mean":
        logit_transform = strategy_cls(state_weights, temperature=strategy_temperature)
    else:
        logit_transform = strategy_cls(state_weights)
        
    stage_set = StageSet(logit_transform=logit_transform)
    
    return bundle, config, stage_set
