// GENERATED by `praxia dw emit` — do not edit by hand.
// Source of truth: agent_assets/workflows/bugfix_simple.yaml
// Regenerate with: praxia dw emit bugfix_simple  (CI gate: praxia dw emit --check)
// Spec: .praxia/docs/specs/260602_pcw-dw-js-emission.md

// Dispatch metadata (informational — matched at the dispatch layer, not here):
//   keywords: bug, fix, regression, error
//   required_capabilities: implementation
export const meta = {
  name: "bugfix-simple",
  description: "Simple bugfix workflow: recon → fix → review",
  phases: [
    { title: "Recon Phase", detail: "recon (kb_research)" },
    { title: "Fix Phase", detail: "fixer (implementation)" },
    { title: "Review Phase", detail: "reviewer (auditing)" },
  ],
};

// §6.3 — gated agent prompts must end with `verdict: <label>`; otherwise routing
// falls back to "advance" (silently advancing past a gate). The emitted prompts
// below append that instruction.
function extractVerdict(text) {
  const m = String(text ?? "").match(/verdict:\s*([a-z_]+)/i);
  return m ? m[1].toLowerCase() : "advance";
}

const BUDGET = { maxRewinds: 3, maxCostUsd: 1.5, maxWalltimeS: 1200 };
const _budget = { rewinds: 0, startMs: Date.now() };

function _checkBudget() {
  if (_budget.rewinds > BUDGET.maxRewinds) {
    throw new Error(`FAIL: max_rewinds exceeded (${_budget.rewinds}/${BUDGET.maxRewinds})`);
  }
  const elapsedS = (Date.now() - _budget.startMs) / 1000;
  if (elapsedS > BUDGET.maxWalltimeS) {
    throw new Error(`FAIL: max_walltime exceeded (${elapsedS.toFixed(0)}s/${BUDGET.maxWalltimeS}s)`);
  }
  // TODO(#854-deferred, see spec §6.4): maxCostUsd is logged, not enforced —
  // no .js session cost API exists in USD denomination yet.
}

function _rewind(label) {
  _budget.rewinds++;
  log(`[budget] rewind ${_budget.rewinds}/${BUDGET.maxRewinds} \u2014 returning to ${label}`);
  _checkBudget();
}

log(`[budget] cost ceiling ${BUDGET.maxCostUsd} USD \u2014 informational only (spec §6.4 deferred)`);

// §6.2 — single labeled loop; `_jump` re-enters a prior phase on a back-edge.
let _jump = null;
outer: while (true) {
  if (_jump === null || _jump === "recon_phase") {
    _jump = null;
    phase("Recon Phase");
    const RECON_PHASE_PROMPT = `[role: recon] [phase: recon_phase]\nTODO(#854): author the real dispatch prompt for this PCW role_step.\nWhen done, respond with 'verdict: <advance>' on its own line so the\nworkflow can route to the next phase (spec §6.3).`;
    const reconPhaseResult = await agent(RECON_PHASE_PROMPT, {
      agentType: "recon",
      label: "Recon Phase",
    });
    const reconPhaseVerdict = extractVerdict(reconPhaseResult);

  }
  if (_jump === null || _jump === "fix_phase") {
    _jump = null;
    phase("Fix Phase");
    const FIX_PHASE_PROMPT = `[role: fixer] [phase: fix_phase]\nTODO(#854): author the real dispatch prompt for this PCW role_step.\nWhen done, respond with 'verdict: <advance|needs_recon>' on its own line so the\nworkflow can route to the next phase (spec §6.3).`;
    const fixPhaseResult = await agent(FIX_PHASE_PROMPT, {
      agentType: "fixer",
      label: "Fix Phase",
    });
    const fixPhaseVerdict = extractVerdict(fixPhaseResult);
    if (fixPhaseVerdict === "needs_recon") { _rewind("Recon Phase"); _jump = "recon_phase"; continue outer; }

  }
  if (_jump === null || _jump === "review_phase") {
    _jump = null;
    phase("Review Phase");
    const REVIEW_PHASE_PROMPT = `[role: reviewer] [phase: review_phase]\nTODO(#854): author the real dispatch prompt for this PCW role_step.\nWhen done, respond with 'verdict: <advance|needs_work>' on its own line so the\nworkflow can route to the next phase (spec §6.3).`;
    const reviewPhaseResult = await agent(REVIEW_PHASE_PROMPT, {
      agentType: "reviewer",
      label: "Review Phase",
    });
    const reviewPhaseVerdict = extractVerdict(reviewPhaseResult);
    if (reviewPhaseVerdict === "advance") { break outer; }
    if (reviewPhaseVerdict === "needs_work") { _rewind("Fix Phase"); _jump = "fix_phase"; continue outer; }

  }
  break outer;
}
